"""Add CareerDNA and CareerMatch, update Roadmap

Revision ID: 0aadcc596873
Revises: 1fc5e1f14cf8
Create Date: 2026-06-16 18:06:29.295711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '0aadcc596873'
down_revision: Union[str, Sequence[str], None] = '1fc5e1f14cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('career_domain', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('growth_potential', sa.Float(), nullable=True),
    sa.Column('suitability_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_matches_career_domain'), 'career_matches', ['career_domain'], unique=False)
    op.create_index(op.f('ix_career_matches_id'), 'career_matches', ['id'], unique=False)
    op.add_column('career_dna', sa.Column('academic_background', sa.String(), nullable=True))
    op.add_column('career_dna', sa.Column('technical_skills', sa.JSON(), nullable=True))
    op.add_column('career_dna', sa.Column('soft_skills', sa.JSON(), nullable=True))
    op.add_column('career_dna', sa.Column('interests', sa.JSON(), nullable=True))
    op.add_column('career_dna', sa.Column('work_preferences', sa.JSON(), nullable=True))
    op.add_column('career_dna', sa.Column('leadership_tendencies', sa.String(), nullable=True))
    op.drop_column('career_dna', 'weaknesses')
    op.drop_column('career_dna', 'work_style')
    op.drop_column('career_dna', 'strengths')
    op.add_column('milestones', sa.Column('recommended_resources', sa.String(), nullable=True))
    op.add_column('milestones', sa.Column('verification_criteria', sa.Text(), nullable=True))
    op.add_column('roadmaps', sa.Column('target_career', sa.String(), nullable=True))
    op.add_column('roadmaps', sa.Column('learning_velocity_modifier', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'learning_velocity_modifier')
    op.drop_column('roadmaps', 'target_career')
    op.drop_column('milestones', 'verification_criteria')
    op.drop_column('milestones', 'recommended_resources')
    op.add_column('career_dna', sa.Column('strengths', sqlite.JSON(), nullable=True))
    op.add_column('career_dna', sa.Column('work_style', sa.VARCHAR(), nullable=True))
    op.add_column('career_dna', sa.Column('weaknesses', sqlite.JSON(), nullable=True))
    op.drop_column('career_dna', 'leadership_tendencies')
    op.drop_column('career_dna', 'work_preferences')
    op.drop_column('career_dna', 'interests')
    op.drop_column('career_dna', 'soft_skills')
    op.drop_column('career_dna', 'technical_skills')
    op.drop_column('career_dna', 'academic_background')
    op.drop_index(op.f('ix_career_matches_id'), table_name='career_matches')
    op.drop_index(op.f('ix_career_matches_career_domain'), table_name='career_matches')
    op.drop_table('career_matches')
    # ### end Alembic commands ###
