"""Add CareerDNA

Revision ID: bacb0cac64e1
Revises: 227ee87c1e45
Create Date: 2026-06-16 16:40:17.491108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacb0cac64e1'
down_revision: Union[str, Sequence[str], None] = '227ee87c1e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_dna',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('weaknesses', sa.JSON(), nullable=True),
    sa.Column('learning_style', sa.String(), nullable=True),
    sa.Column('work_style', sa.String(), nullable=True),
    sa.Column('risk_tolerance', sa.String(), nullable=True),
    sa.Column('motivation_profile', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_dna_id'), 'career_dna', ['id'], unique=False)
    op.create_index(op.f('ix_career_dna_user_id'), 'career_dna', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_dna_user_id'), table_name='career_dna')
    op.drop_index(op.f('ix_career_dna_id'), table_name='career_dna')
    op.drop_table('career_dna')
    # ### end Alembic commands ###
